name: Auto Assign Issues

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Assign issue
        uses: actions/github-script@v5
        with:
          script: |
            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: ['kaitlyncornish01']
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
